name: "Run Release Please"

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.TOKEN }}
          release-type: simple
